### ISSUE TITLE
Need to remove additional data in CSV file

### ISSUE THREAD

**Issue by bhushankhope** [cns-iu/humanatlas.io#319]
In release.csv file for asctb tables, in Large Intestine row, there is one additional data. This row has 1 column data extra than all the other rows, due to this the Metadata URL is not mapped correctly to the Organ. Please let me know if you need help in finding the issue.
https://humanatlas.io/asctb-tables
2nd HRA Release (v1.1)
[release2.csv](https://github.com/cns-iu/humanatlas.io/files/12794515/release2.csv)

**Comment by emquardokus** [comment]
@bhushankhope 
I figured out what the problem was!  I just used the ASCT+B reporter viewed v1.1 large intestine table and looked at Report.
It appears that maybe there had been a problem reading 1156 and this was split into two columns 1 and 156 therefore shifting the columns by 1 and then the url link was shifted over.

The 352 number was revised to 353 as per ASCT+B reporter Report:
<img width="1195" alt="Screenshot 2023-10-03 at 3 35 56 PM" src="https://github.com/cns-iu/humanatlas.io/assets/47257000/6f9ae076-7599-4c38-b3c2-ccf68f56ff19">



This shows total biomarker number genes + proteins
<img width="628" alt="Screenshot 2023-10-03 at 3 34 57 PM" src="https://github.com/cns-iu/humanatlas.io/assets/47257000/c7f2c48a-9de2-4f39-bb85-d9ad4561fdce">

Genes only number
<img width="590" alt="Screenshot 2023-10-03 at 3 32 29 PM" src="https://github.com/cns-iu/humanatlas.io/assets/47257000/4cc0917c-c5a4-4570-bcf1-1ab9173116ce">

Updated release2.csv attached
[release2.csv](https://github.com/cns-iu/humanatlas.io/files/12796403/release2.csv)

**Comment by bhushankhope** [comment]
Updated CSV in PR #320
