### ISSUE TITLE
New menu items for orphaned resources found in 4th release notes only

### ISSUE THREAD

**Issue by emquardokus** [cns-iu/humanatlas.io#56]
@libby-maier, @bherr2, @katyb 
Three resources exist only as mentions in the 4th release notes: 
- HRA Previews pilots 1-5
- HRA 24 Hour Event
- ASCT+B Ontology Validations

I did not realize these existed until I re-read the updated release notes.  Very few people will see these items if only present there.  

1. Should we showcase them under one of the existing menus: data, CCF ontology, tools, training & outreach?

2. Should we create a new menu for "events" or "meetings & events"  like the HRA 24 hour event and presumably future (or maybe some past events like the 2020 March NIH/HCA meeting where ASCT+B WG sprouted from?

**Possible ideas for where to put them:**
- Should the HRA Previews pilots 1-5 --> training and outreach?
- Should ASCT+B Ontology Validations --> CCF Ontology?
- HRA 24 Hour Event --> new menu called Events?  or Meeting & Events ? otherwise, if only the current choices then the only one that makes sense is possibly training and outreach

**Comment by katyb** [comment]
Yes,

  *   HRA Previews pilots 1-5
  *   HRA 24 Hour Event
Should be added to

***@***.***


  *   ASCT+B Ontology Validations
Should be added to Tools.

Need to unify
HRA/CCF/ASCT+B Ontology -> HRA Ontology – everywhere. Also in Menu.
k

From: emquardokus ***@***.***>
Sent: Friday, January 6, 2023 10:03 AM
To: cns-iu/humanatlas.io ***@***.***>
Cc: Borner, Katy ***@***.***>; Mention ***@***.***>
Subject: [cns-iu/humanatlas.io] New menu items for orphaned resources found in 4th release notes only (Issue #56)


@libby-maier<https://github.com/libby-maier>, @bherr2<https://github.com/bherr2>, @katyb<https://github.com/katyb>
Three resources exist only as mentions in the 4th release notes:

  *   HRA Previews pilots 1-5
  *   HRA 24 Hour Event
  *   ASCT+B Ontology Validations

I did not realize these existed until I re-read the updated release notes. Very few people will see these items if only present there.

  1.  Should we showcase them under one of the existing menus: data, CCF ontology, tools, training & outreach?
  2.  Should we create a new menu for "events" or "meetings & events" like the HRA 24 hour event and presumably future (or maybe some past events like the 2020 March NIH/HCA meeting where ASCT+B WG sprouted from?

Possible ideas for where to put them:

  *   Should the HRA Previews pilots 1-5 --> training and outreach?
  *   Should ASCT+B Ontology Validations --> CCF Ontology?
  *   HRA 24 Hour Event --> new menu called Events? or Meeting & Events ? otherwise, if only the current choices then the only one that makes sense is possibly training and outreach

**Comment by emquardokus** [comment]
@katyb, @bherr2 
As demonstrated in the Indigo Ibex, and I felt the same way, I had never heard of “scrollytelling” and did not know what it meant without looking it up last night. 

We should have a definition of this on the HRA portal with the scrollytelling series because I am willing to bet that most wet bench scientists (as well as NIH etc)  will not have encountered this word despite perhaps interacting with content that may have been using this method.

I noticed that Bhushan had commented out both the" 24 hour Human Reference Atlas event" and the "Scrollytelling series" for the HRA preview pilots for the Training & Outreach menu awaiting their completion.

Which terminology should go in the menu dropdown : "Scrolling telling series" or "HRA preview pilots" or something else like the actual listing of them in the dropdown menu?

It would be good to capture this now and I can get it into the GitHub repo as either an issue or pull request as change.
These are the Pilots already existing with markdown files in the hra-previews GitHub repository.

Pilot 1 Preview: ASCT+B Reporter Comparison
Pilot 2 Preview: Vasculature CCF Visualization
Pilot 3 Preview: HRA vs. Experimental Data
Pilot 4 Preview: Scrollytelling Series
Pilot 5 Preview: Comparing Tabula Sapiens to the Human Reference Atlas
Pilot 6 Preview: FTU Segmentation
Pilot 7 Preview: CCF Tissue Block Annotation: Mesh-Level Collision Detection

========
These are the proposed scrollytelling series topics

What Is an HRA (and Why Do We Really, Really Need One)?
Get to Know Your Anatomical Structures!
Shared Pathways: A Vasculature-Based Coordinate System
Call in the Experts: Validating the Human Reference Atlas
How to Identify and Locate Cell Type Populations
Up Close and Virtual: Using the VR Organ Gallery for Teaching and Training
What Is a Functional Tissue Unit?
How All the Letters Connect: Making Sense of the ASCT+B Tables
Who Uses the Human Reference Atlas and Why?
=============

**Comment by emquardokus** [comment]
**These items were already resolved: **
HRA 24 Hour Event—> training an outreach (I suggested possibly an “Events” menu item as an alternative)
ASCT+B Ontology Validations—> tools
**Left to resolve: **
HRA Previews pilots 1-5 ——> these items are still in the HRA Release notes under Data menu, but I believe that some of these are still not completely done yet, but where should these live?

**Comment by libby-maier** [comment]
# UX/UI To Dos In Figma:

## ASCT+B Ontology Validations
- [ ] Remove ASCT+B Ontology Validations from the mobile & desktop menu
- [ ] Add ASCT+B Ontology Validation section
- [ ] Pair with @emquardokus for section short description
- [ ] Add button to sign up form on ASCT+B Table page

## HRA 24 Hour Event
- [ ]  Write a dev request to update the route to the event page instead of the YouTube playlist

## Preview/Pilots listing:
- [ ]  Add preview/pilots listing to Training and Outreach section
